package nl.han.jefmk.surfaces;

public enum TileType {
    CEILING,
    FLOOR,
    WALL_LEFT,
    WALL_RIGHT,
    CORNER_TOP_LEFT,
    CORNER_TOP_RIGHT,
    CORNER_BOTTOM_LEFT,
    CORNER_BOTTOM_RIGHT,
    OUTER_CORNER_TOP_LEFT,
    OUTER_CORNER_TOP_RIGHT,
    OUTER_CORNER_BOTTOM_LEFT,
    OUTER_CORNER_BOTTOM_RIGHT,
    WALL_FILLING
}
